// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BlockStorage is the predicate function for blockstorage builders.
type BlockStorage func(*sql.Selector)

// IPAddress is the predicate function for ipaddress builders.
type IPAddress func(*sql.Selector)

// Instances is the predicate function for instances builders.
type Instances func(*sql.Selector)

// LoadBalancer is the predicate function for loadbalancer builders.
type LoadBalancer func(*sql.Selector)

// ObjectStorage is the predicate function for objectstorage builders.
type ObjectStorage func(*sql.Selector)

// Panier is the predicate function for panier builders.
type Panier func(*sql.Selector)

// PanierBlockStorage is the predicate function for panierblockstorage builders.
type PanierBlockStorage func(*sql.Selector)

// PanierIPAddress is the predicate function for panieripaddress builders.
type PanierIPAddress func(*sql.Selector)

// PanierInstances is the predicate function for panierinstances builders.
type PanierInstances func(*sql.Selector)

// PanierLoadBalancer is the predicate function for panierloadbalancer builders.
type PanierLoadBalancer func(*sql.Selector)

// PanierObjectStorage is the predicate function for panierobjectstorage builders.
type PanierObjectStorage func(*sql.Selector)
