// Code generated by ent, DO NOT EDIT.

package objectstorage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the objectstorage type in the database.
	Label = "object_storage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// EdgePanierObjectStorage holds the string denoting the panierobjectstorage edge name in mutations.
	EdgePanierObjectStorage = "panierObjectStorage"
	// Table holds the table name of the objectstorage in the database.
	Table = "object_storages"
	// PanierObjectStorageTable is the table that holds the panierObjectStorage relation/edge.
	PanierObjectStorageTable = "panier_object_storages"
	// PanierObjectStorageInverseTable is the table name for the PanierObjectStorage entity.
	// It exists in this package in order to avoid circular dependency with the "panierobjectstorage" package.
	PanierObjectStorageInverseTable = "panier_object_storages"
	// PanierObjectStorageColumn is the table column denoting the panierObjectStorage relation/edge.
	PanierObjectStorageColumn = "objectStorage_id"
)

// Columns holds all SQL columns for objectstorage fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPrice,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ObjectStorage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the Name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrice orders the results by the Price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByPanierObjectStorageCount orders the results by panierObjectStorage count.
func ByPanierObjectStorageCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPanierObjectStorageStep(), opts...)
	}
}

// ByPanierObjectStorage orders the results by panierObjectStorage terms.
func ByPanierObjectStorage(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPanierObjectStorageStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPanierObjectStorageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PanierObjectStorageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PanierObjectStorageTable, PanierObjectStorageColumn),
	)
}
