// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/instances"
	"backend/ent/panierinstances"
	"backend/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InstancesQuery is the builder for querying Instances entities.
type InstancesQuery struct {
	config
	ctx                 *QueryContext
	order               []instances.OrderOption
	inters              []Interceptor
	predicates          []predicate.Instances
	withPanierInstances *PanierInstancesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InstancesQuery builder.
func (iq *InstancesQuery) Where(ps ...predicate.Instances) *InstancesQuery {
	iq.predicates = append(iq.predicates, ps...)
	return iq
}

// Limit the number of records to be returned by this query.
func (iq *InstancesQuery) Limit(limit int) *InstancesQuery {
	iq.ctx.Limit = &limit
	return iq
}

// Offset to start from.
func (iq *InstancesQuery) Offset(offset int) *InstancesQuery {
	iq.ctx.Offset = &offset
	return iq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (iq *InstancesQuery) Unique(unique bool) *InstancesQuery {
	iq.ctx.Unique = &unique
	return iq
}

// Order specifies how the records should be ordered.
func (iq *InstancesQuery) Order(o ...instances.OrderOption) *InstancesQuery {
	iq.order = append(iq.order, o...)
	return iq
}

// QueryPanierInstances chains the current query on the "panierInstances" edge.
func (iq *InstancesQuery) QueryPanierInstances() *PanierInstancesQuery {
	query := (&PanierInstancesClient{config: iq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := iq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := iq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(instances.Table, instances.FieldID, selector),
			sqlgraph.To(panierinstances.Table, panierinstances.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, instances.PanierInstancesTable, instances.PanierInstancesColumn),
		)
		fromU = sqlgraph.SetNeighbors(iq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Instances entity from the query.
// Returns a *NotFoundError when no Instances was found.
func (iq *InstancesQuery) First(ctx context.Context) (*Instances, error) {
	nodes, err := iq.Limit(1).All(setContextOp(ctx, iq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{instances.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (iq *InstancesQuery) FirstX(ctx context.Context) *Instances {
	node, err := iq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Instances ID from the query.
// Returns a *NotFoundError when no Instances ID was found.
func (iq *InstancesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iq.Limit(1).IDs(setContextOp(ctx, iq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{instances.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (iq *InstancesQuery) FirstIDX(ctx context.Context) int {
	id, err := iq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Instances entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Instances entity is found.
// Returns a *NotFoundError when no Instances entities are found.
func (iq *InstancesQuery) Only(ctx context.Context) (*Instances, error) {
	nodes, err := iq.Limit(2).All(setContextOp(ctx, iq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{instances.Label}
	default:
		return nil, &NotSingularError{instances.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (iq *InstancesQuery) OnlyX(ctx context.Context) *Instances {
	node, err := iq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Instances ID in the query.
// Returns a *NotSingularError when more than one Instances ID is found.
// Returns a *NotFoundError when no entities are found.
func (iq *InstancesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = iq.Limit(2).IDs(setContextOp(ctx, iq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{instances.Label}
	default:
		err = &NotSingularError{instances.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (iq *InstancesQuery) OnlyIDX(ctx context.Context) int {
	id, err := iq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InstancesSlice.
func (iq *InstancesQuery) All(ctx context.Context) ([]*Instances, error) {
	ctx = setContextOp(ctx, iq.ctx, "All")
	if err := iq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Instances, *InstancesQuery]()
	return withInterceptors[[]*Instances](ctx, iq, qr, iq.inters)
}

// AllX is like All, but panics if an error occurs.
func (iq *InstancesQuery) AllX(ctx context.Context) []*Instances {
	nodes, err := iq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Instances IDs.
func (iq *InstancesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if iq.ctx.Unique == nil && iq.path != nil {
		iq.Unique(true)
	}
	ctx = setContextOp(ctx, iq.ctx, "IDs")
	if err = iq.Select(instances.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (iq *InstancesQuery) IDsX(ctx context.Context) []int {
	ids, err := iq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (iq *InstancesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, iq.ctx, "Count")
	if err := iq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, iq, querierCount[*InstancesQuery](), iq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (iq *InstancesQuery) CountX(ctx context.Context) int {
	count, err := iq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (iq *InstancesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, iq.ctx, "Exist")
	switch _, err := iq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (iq *InstancesQuery) ExistX(ctx context.Context) bool {
	exist, err := iq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InstancesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (iq *InstancesQuery) Clone() *InstancesQuery {
	if iq == nil {
		return nil
	}
	return &InstancesQuery{
		config:              iq.config,
		ctx:                 iq.ctx.Clone(),
		order:               append([]instances.OrderOption{}, iq.order...),
		inters:              append([]Interceptor{}, iq.inters...),
		predicates:          append([]predicate.Instances{}, iq.predicates...),
		withPanierInstances: iq.withPanierInstances.Clone(),
		// clone intermediate query.
		sql:  iq.sql.Clone(),
		path: iq.path,
	}
}

// WithPanierInstances tells the query-builder to eager-load the nodes that are connected to
// the "panierInstances" edge. The optional arguments are used to configure the query builder of the edge.
func (iq *InstancesQuery) WithPanierInstances(opts ...func(*PanierInstancesQuery)) *InstancesQuery {
	query := (&PanierInstancesClient{config: iq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	iq.withPanierInstances = query
	return iq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Instances.Query().
//		GroupBy(instances.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (iq *InstancesQuery) GroupBy(field string, fields ...string) *InstancesGroupBy {
	iq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InstancesGroupBy{build: iq}
	grbuild.flds = &iq.ctx.Fields
	grbuild.label = instances.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.Instances.Query().
//		Select(instances.FieldName).
//		Scan(ctx, &v)
func (iq *InstancesQuery) Select(fields ...string) *InstancesSelect {
	iq.ctx.Fields = append(iq.ctx.Fields, fields...)
	sbuild := &InstancesSelect{InstancesQuery: iq}
	sbuild.label = instances.Label
	sbuild.flds, sbuild.scan = &iq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InstancesSelect configured with the given aggregations.
func (iq *InstancesQuery) Aggregate(fns ...AggregateFunc) *InstancesSelect {
	return iq.Select().Aggregate(fns...)
}

func (iq *InstancesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range iq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, iq); err != nil {
				return err
			}
		}
	}
	for _, f := range iq.ctx.Fields {
		if !instances.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if iq.path != nil {
		prev, err := iq.path(ctx)
		if err != nil {
			return err
		}
		iq.sql = prev
	}
	return nil
}

func (iq *InstancesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Instances, error) {
	var (
		nodes       = []*Instances{}
		_spec       = iq.querySpec()
		loadedTypes = [1]bool{
			iq.withPanierInstances != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Instances).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Instances{config: iq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, iq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := iq.withPanierInstances; query != nil {
		if err := iq.loadPanierInstances(ctx, query, nodes,
			func(n *Instances) { n.Edges.PanierInstances = []*PanierInstances{} },
			func(n *Instances, e *PanierInstances) { n.Edges.PanierInstances = append(n.Edges.PanierInstances, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (iq *InstancesQuery) loadPanierInstances(ctx context.Context, query *PanierInstancesQuery, nodes []*Instances, init func(*Instances), assign func(*Instances, *PanierInstances)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Instances)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PanierInstances(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(instances.PanierInstancesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.instance_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "instance_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "instance_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (iq *InstancesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := iq.querySpec()
	_spec.Node.Columns = iq.ctx.Fields
	if len(iq.ctx.Fields) > 0 {
		_spec.Unique = iq.ctx.Unique != nil && *iq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, iq.driver, _spec)
}

func (iq *InstancesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(instances.Table, instances.Columns, sqlgraph.NewFieldSpec(instances.FieldID, field.TypeInt))
	_spec.From = iq.sql
	if unique := iq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if iq.path != nil {
		_spec.Unique = true
	}
	if fields := iq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instances.FieldID)
		for i := range fields {
			if fields[i] != instances.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := iq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := iq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := iq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := iq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (iq *InstancesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(iq.driver.Dialect())
	t1 := builder.Table(instances.Table)
	columns := iq.ctx.Fields
	if len(columns) == 0 {
		columns = instances.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if iq.sql != nil {
		selector = iq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if iq.ctx.Unique != nil && *iq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range iq.predicates {
		p(selector)
	}
	for _, p := range iq.order {
		p(selector)
	}
	if offset := iq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := iq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// InstancesGroupBy is the group-by builder for Instances entities.
type InstancesGroupBy struct {
	selector
	build *InstancesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (igb *InstancesGroupBy) Aggregate(fns ...AggregateFunc) *InstancesGroupBy {
	igb.fns = append(igb.fns, fns...)
	return igb
}

// Scan applies the selector query and scans the result into the given value.
func (igb *InstancesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, igb.build.ctx, "GroupBy")
	if err := igb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InstancesQuery, *InstancesGroupBy](ctx, igb.build, igb, igb.build.inters, v)
}

func (igb *InstancesGroupBy) sqlScan(ctx context.Context, root *InstancesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(igb.fns))
	for _, fn := range igb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*igb.flds)+len(igb.fns))
		for _, f := range *igb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*igb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := igb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InstancesSelect is the builder for selecting fields of Instances entities.
type InstancesSelect struct {
	*InstancesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (is *InstancesSelect) Aggregate(fns ...AggregateFunc) *InstancesSelect {
	is.fns = append(is.fns, fns...)
	return is
}

// Scan applies the selector query and scans the result into the given value.
func (is *InstancesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, is.ctx, "Select")
	if err := is.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InstancesQuery, *InstancesSelect](ctx, is.InstancesQuery, is, is.inters, v)
}

func (is *InstancesSelect) sqlScan(ctx context.Context, root *InstancesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(is.fns))
	for _, fn := range is.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*is.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := is.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
