// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/loadbalancer"
	"backend/ent/panierloadbalancer"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LoadBalancerCreate is the builder for creating a LoadBalancer entity.
type LoadBalancerCreate struct {
	config
	mutation *LoadBalancerMutation
	hooks    []Hook
}

// SetName sets the "Name" field.
func (lbc *LoadBalancerCreate) SetName(s string) *LoadBalancerCreate {
	lbc.mutation.SetName(s)
	return lbc
}

// SetPrice sets the "Price" field.
func (lbc *LoadBalancerCreate) SetPrice(f float64) *LoadBalancerCreate {
	lbc.mutation.SetPrice(f)
	return lbc
}

// SetID sets the "id" field.
func (lbc *LoadBalancerCreate) SetID(i int) *LoadBalancerCreate {
	lbc.mutation.SetID(i)
	return lbc
}

// AddPanierLoadBalancerIDs adds the "panierLoadBalancer" edge to the PanierLoadBalancer entity by IDs.
func (lbc *LoadBalancerCreate) AddPanierLoadBalancerIDs(ids ...int) *LoadBalancerCreate {
	lbc.mutation.AddPanierLoadBalancerIDs(ids...)
	return lbc
}

// AddPanierLoadBalancer adds the "panierLoadBalancer" edges to the PanierLoadBalancer entity.
func (lbc *LoadBalancerCreate) AddPanierLoadBalancer(p ...*PanierLoadBalancer) *LoadBalancerCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return lbc.AddPanierLoadBalancerIDs(ids...)
}

// Mutation returns the LoadBalancerMutation object of the builder.
func (lbc *LoadBalancerCreate) Mutation() *LoadBalancerMutation {
	return lbc.mutation
}

// Save creates the LoadBalancer in the database.
func (lbc *LoadBalancerCreate) Save(ctx context.Context) (*LoadBalancer, error) {
	return withHooks(ctx, lbc.sqlSave, lbc.mutation, lbc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lbc *LoadBalancerCreate) SaveX(ctx context.Context) *LoadBalancer {
	v, err := lbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lbc *LoadBalancerCreate) Exec(ctx context.Context) error {
	_, err := lbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lbc *LoadBalancerCreate) ExecX(ctx context.Context) {
	if err := lbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lbc *LoadBalancerCreate) check() error {
	if _, ok := lbc.mutation.Name(); !ok {
		return &ValidationError{Name: "Name", err: errors.New(`ent: missing required field "LoadBalancer.Name"`)}
	}
	if _, ok := lbc.mutation.Price(); !ok {
		return &ValidationError{Name: "Price", err: errors.New(`ent: missing required field "LoadBalancer.Price"`)}
	}
	return nil
}

func (lbc *LoadBalancerCreate) sqlSave(ctx context.Context) (*LoadBalancer, error) {
	if err := lbc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	lbc.mutation.id = &_node.ID
	lbc.mutation.done = true
	return _node, nil
}

func (lbc *LoadBalancerCreate) createSpec() (*LoadBalancer, *sqlgraph.CreateSpec) {
	var (
		_node = &LoadBalancer{config: lbc.config}
		_spec = sqlgraph.NewCreateSpec(loadbalancer.Table, sqlgraph.NewFieldSpec(loadbalancer.FieldID, field.TypeInt))
	)
	if id, ok := lbc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := lbc.mutation.Name(); ok {
		_spec.SetField(loadbalancer.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := lbc.mutation.Price(); ok {
		_spec.SetField(loadbalancer.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if nodes := lbc.mutation.PanierLoadBalancerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loadbalancer.PanierLoadBalancerTable,
			Columns: []string{loadbalancer.PanierLoadBalancerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(panierloadbalancer.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LoadBalancerCreateBulk is the builder for creating many LoadBalancer entities in bulk.
type LoadBalancerCreateBulk struct {
	config
	builders []*LoadBalancerCreate
}

// Save creates the LoadBalancer entities in the database.
func (lbcb *LoadBalancerCreateBulk) Save(ctx context.Context) ([]*LoadBalancer, error) {
	specs := make([]*sqlgraph.CreateSpec, len(lbcb.builders))
	nodes := make([]*LoadBalancer, len(lbcb.builders))
	mutators := make([]Mutator, len(lbcb.builders))
	for i := range lbcb.builders {
		func(i int, root context.Context) {
			builder := lbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoadBalancerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lbcb *LoadBalancerCreateBulk) SaveX(ctx context.Context) []*LoadBalancer {
	v, err := lbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lbcb *LoadBalancerCreateBulk) Exec(ctx context.Context) error {
	_, err := lbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lbcb *LoadBalancerCreateBulk) ExecX(ctx context.Context) {
	if err := lbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
