// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/objectstorage"
	"backend/ent/panierobjectstorage"
	"backend/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ObjectStorageQuery is the builder for querying ObjectStorage entities.
type ObjectStorageQuery struct {
	config
	ctx                     *QueryContext
	order                   []objectstorage.OrderOption
	inters                  []Interceptor
	predicates              []predicate.ObjectStorage
	withPanierObjectStorage *PanierObjectStorageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ObjectStorageQuery builder.
func (osq *ObjectStorageQuery) Where(ps ...predicate.ObjectStorage) *ObjectStorageQuery {
	osq.predicates = append(osq.predicates, ps...)
	return osq
}

// Limit the number of records to be returned by this query.
func (osq *ObjectStorageQuery) Limit(limit int) *ObjectStorageQuery {
	osq.ctx.Limit = &limit
	return osq
}

// Offset to start from.
func (osq *ObjectStorageQuery) Offset(offset int) *ObjectStorageQuery {
	osq.ctx.Offset = &offset
	return osq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (osq *ObjectStorageQuery) Unique(unique bool) *ObjectStorageQuery {
	osq.ctx.Unique = &unique
	return osq
}

// Order specifies how the records should be ordered.
func (osq *ObjectStorageQuery) Order(o ...objectstorage.OrderOption) *ObjectStorageQuery {
	osq.order = append(osq.order, o...)
	return osq
}

// QueryPanierObjectStorage chains the current query on the "panierObjectStorage" edge.
func (osq *ObjectStorageQuery) QueryPanierObjectStorage() *PanierObjectStorageQuery {
	query := (&PanierObjectStorageClient{config: osq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := osq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := osq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(objectstorage.Table, objectstorage.FieldID, selector),
			sqlgraph.To(panierobjectstorage.Table, panierobjectstorage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, objectstorage.PanierObjectStorageTable, objectstorage.PanierObjectStorageColumn),
		)
		fromU = sqlgraph.SetNeighbors(osq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ObjectStorage entity from the query.
// Returns a *NotFoundError when no ObjectStorage was found.
func (osq *ObjectStorageQuery) First(ctx context.Context) (*ObjectStorage, error) {
	nodes, err := osq.Limit(1).All(setContextOp(ctx, osq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{objectstorage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (osq *ObjectStorageQuery) FirstX(ctx context.Context) *ObjectStorage {
	node, err := osq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ObjectStorage ID from the query.
// Returns a *NotFoundError when no ObjectStorage ID was found.
func (osq *ObjectStorageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = osq.Limit(1).IDs(setContextOp(ctx, osq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{objectstorage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (osq *ObjectStorageQuery) FirstIDX(ctx context.Context) int {
	id, err := osq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ObjectStorage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ObjectStorage entity is found.
// Returns a *NotFoundError when no ObjectStorage entities are found.
func (osq *ObjectStorageQuery) Only(ctx context.Context) (*ObjectStorage, error) {
	nodes, err := osq.Limit(2).All(setContextOp(ctx, osq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{objectstorage.Label}
	default:
		return nil, &NotSingularError{objectstorage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (osq *ObjectStorageQuery) OnlyX(ctx context.Context) *ObjectStorage {
	node, err := osq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ObjectStorage ID in the query.
// Returns a *NotSingularError when more than one ObjectStorage ID is found.
// Returns a *NotFoundError when no entities are found.
func (osq *ObjectStorageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = osq.Limit(2).IDs(setContextOp(ctx, osq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{objectstorage.Label}
	default:
		err = &NotSingularError{objectstorage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (osq *ObjectStorageQuery) OnlyIDX(ctx context.Context) int {
	id, err := osq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ObjectStorages.
func (osq *ObjectStorageQuery) All(ctx context.Context) ([]*ObjectStorage, error) {
	ctx = setContextOp(ctx, osq.ctx, "All")
	if err := osq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ObjectStorage, *ObjectStorageQuery]()
	return withInterceptors[[]*ObjectStorage](ctx, osq, qr, osq.inters)
}

// AllX is like All, but panics if an error occurs.
func (osq *ObjectStorageQuery) AllX(ctx context.Context) []*ObjectStorage {
	nodes, err := osq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ObjectStorage IDs.
func (osq *ObjectStorageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if osq.ctx.Unique == nil && osq.path != nil {
		osq.Unique(true)
	}
	ctx = setContextOp(ctx, osq.ctx, "IDs")
	if err = osq.Select(objectstorage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (osq *ObjectStorageQuery) IDsX(ctx context.Context) []int {
	ids, err := osq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (osq *ObjectStorageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, osq.ctx, "Count")
	if err := osq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, osq, querierCount[*ObjectStorageQuery](), osq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (osq *ObjectStorageQuery) CountX(ctx context.Context) int {
	count, err := osq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (osq *ObjectStorageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, osq.ctx, "Exist")
	switch _, err := osq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (osq *ObjectStorageQuery) ExistX(ctx context.Context) bool {
	exist, err := osq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ObjectStorageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (osq *ObjectStorageQuery) Clone() *ObjectStorageQuery {
	if osq == nil {
		return nil
	}
	return &ObjectStorageQuery{
		config:                  osq.config,
		ctx:                     osq.ctx.Clone(),
		order:                   append([]objectstorage.OrderOption{}, osq.order...),
		inters:                  append([]Interceptor{}, osq.inters...),
		predicates:              append([]predicate.ObjectStorage{}, osq.predicates...),
		withPanierObjectStorage: osq.withPanierObjectStorage.Clone(),
		// clone intermediate query.
		sql:  osq.sql.Clone(),
		path: osq.path,
	}
}

// WithPanierObjectStorage tells the query-builder to eager-load the nodes that are connected to
// the "panierObjectStorage" edge. The optional arguments are used to configure the query builder of the edge.
func (osq *ObjectStorageQuery) WithPanierObjectStorage(opts ...func(*PanierObjectStorageQuery)) *ObjectStorageQuery {
	query := (&PanierObjectStorageClient{config: osq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	osq.withPanierObjectStorage = query
	return osq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ObjectStorage.Query().
//		GroupBy(objectstorage.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (osq *ObjectStorageQuery) GroupBy(field string, fields ...string) *ObjectStorageGroupBy {
	osq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ObjectStorageGroupBy{build: osq}
	grbuild.flds = &osq.ctx.Fields
	grbuild.label = objectstorage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"Name,omitempty"`
//	}
//
//	client.ObjectStorage.Query().
//		Select(objectstorage.FieldName).
//		Scan(ctx, &v)
func (osq *ObjectStorageQuery) Select(fields ...string) *ObjectStorageSelect {
	osq.ctx.Fields = append(osq.ctx.Fields, fields...)
	sbuild := &ObjectStorageSelect{ObjectStorageQuery: osq}
	sbuild.label = objectstorage.Label
	sbuild.flds, sbuild.scan = &osq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ObjectStorageSelect configured with the given aggregations.
func (osq *ObjectStorageQuery) Aggregate(fns ...AggregateFunc) *ObjectStorageSelect {
	return osq.Select().Aggregate(fns...)
}

func (osq *ObjectStorageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range osq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, osq); err != nil {
				return err
			}
		}
	}
	for _, f := range osq.ctx.Fields {
		if !objectstorage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if osq.path != nil {
		prev, err := osq.path(ctx)
		if err != nil {
			return err
		}
		osq.sql = prev
	}
	return nil
}

func (osq *ObjectStorageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ObjectStorage, error) {
	var (
		nodes       = []*ObjectStorage{}
		_spec       = osq.querySpec()
		loadedTypes = [1]bool{
			osq.withPanierObjectStorage != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ObjectStorage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ObjectStorage{config: osq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, osq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := osq.withPanierObjectStorage; query != nil {
		if err := osq.loadPanierObjectStorage(ctx, query, nodes,
			func(n *ObjectStorage) { n.Edges.PanierObjectStorage = []*PanierObjectStorage{} },
			func(n *ObjectStorage, e *PanierObjectStorage) {
				n.Edges.PanierObjectStorage = append(n.Edges.PanierObjectStorage, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (osq *ObjectStorageQuery) loadPanierObjectStorage(ctx context.Context, query *PanierObjectStorageQuery, nodes []*ObjectStorage, init func(*ObjectStorage), assign func(*ObjectStorage, *PanierObjectStorage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ObjectStorage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PanierObjectStorage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(objectstorage.PanierObjectStorageColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.objectStorage_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "objectStorage_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "objectStorage_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (osq *ObjectStorageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := osq.querySpec()
	_spec.Node.Columns = osq.ctx.Fields
	if len(osq.ctx.Fields) > 0 {
		_spec.Unique = osq.ctx.Unique != nil && *osq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, osq.driver, _spec)
}

func (osq *ObjectStorageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(objectstorage.Table, objectstorage.Columns, sqlgraph.NewFieldSpec(objectstorage.FieldID, field.TypeInt))
	_spec.From = osq.sql
	if unique := osq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if osq.path != nil {
		_spec.Unique = true
	}
	if fields := osq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, objectstorage.FieldID)
		for i := range fields {
			if fields[i] != objectstorage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := osq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := osq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := osq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := osq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (osq *ObjectStorageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(osq.driver.Dialect())
	t1 := builder.Table(objectstorage.Table)
	columns := osq.ctx.Fields
	if len(columns) == 0 {
		columns = objectstorage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if osq.sql != nil {
		selector = osq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if osq.ctx.Unique != nil && *osq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range osq.predicates {
		p(selector)
	}
	for _, p := range osq.order {
		p(selector)
	}
	if offset := osq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := osq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ObjectStorageGroupBy is the group-by builder for ObjectStorage entities.
type ObjectStorageGroupBy struct {
	selector
	build *ObjectStorageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (osgb *ObjectStorageGroupBy) Aggregate(fns ...AggregateFunc) *ObjectStorageGroupBy {
	osgb.fns = append(osgb.fns, fns...)
	return osgb
}

// Scan applies the selector query and scans the result into the given value.
func (osgb *ObjectStorageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, osgb.build.ctx, "GroupBy")
	if err := osgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ObjectStorageQuery, *ObjectStorageGroupBy](ctx, osgb.build, osgb, osgb.build.inters, v)
}

func (osgb *ObjectStorageGroupBy) sqlScan(ctx context.Context, root *ObjectStorageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(osgb.fns))
	for _, fn := range osgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*osgb.flds)+len(osgb.fns))
		for _, f := range *osgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*osgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := osgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ObjectStorageSelect is the builder for selecting fields of ObjectStorage entities.
type ObjectStorageSelect struct {
	*ObjectStorageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oss *ObjectStorageSelect) Aggregate(fns ...AggregateFunc) *ObjectStorageSelect {
	oss.fns = append(oss.fns, fns...)
	return oss
}

// Scan applies the selector query and scans the result into the given value.
func (oss *ObjectStorageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oss.ctx, "Select")
	if err := oss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ObjectStorageQuery, *ObjectStorageSelect](ctx, oss.ObjectStorageQuery, oss, oss.inters, v)
}

func (oss *ObjectStorageSelect) sqlScan(ctx context.Context, root *ObjectStorageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oss.fns))
	for _, fn := range oss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
