// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/blockstorage"
	"backend/ent/panier"
	"backend/ent/panierblockstorage"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PanierBlockStorage is the model entity for the PanierBlockStorage schema.
type PanierBlockStorage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PanierBlockStorageQuery when eager-loading is set.
	Edges                              PanierBlockStorageEdges `json:"edges"`
	block_storage_panier_block_storage *int
	panier_panier_block_storage        *int
	selectValues                       sql.SelectValues
}

// PanierBlockStorageEdges holds the relations/edges for other nodes in the graph.
type PanierBlockStorageEdges struct {
	// Panier holds the value of the panier edge.
	Panier *Panier `json:"panier,omitempty"`
	// BlockStorage holds the value of the blockStorage edge.
	BlockStorage *BlockStorage `json:"blockStorage,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PanierOrErr returns the Panier value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PanierBlockStorageEdges) PanierOrErr() (*Panier, error) {
	if e.loadedTypes[0] {
		if e.Panier == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: panier.Label}
		}
		return e.Panier, nil
	}
	return nil, &NotLoadedError{edge: "panier"}
}

// BlockStorageOrErr returns the BlockStorage value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PanierBlockStorageEdges) BlockStorageOrErr() (*BlockStorage, error) {
	if e.loadedTypes[1] {
		if e.BlockStorage == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: blockstorage.Label}
		}
		return e.BlockStorage, nil
	}
	return nil, &NotLoadedError{edge: "blockStorage"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PanierBlockStorage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case panierblockstorage.FieldID, panierblockstorage.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case panierblockstorage.ForeignKeys[0]: // block_storage_panier_block_storage
			values[i] = new(sql.NullInt64)
		case panierblockstorage.ForeignKeys[1]: // panier_panier_block_storage
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PanierBlockStorage fields.
func (pbs *PanierBlockStorage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case panierblockstorage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pbs.ID = int(value.Int64)
		case panierblockstorage.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				pbs.Quantity = int(value.Int64)
			}
		case panierblockstorage.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field block_storage_panier_block_storage", value)
			} else if value.Valid {
				pbs.block_storage_panier_block_storage = new(int)
				*pbs.block_storage_panier_block_storage = int(value.Int64)
			}
		case panierblockstorage.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field panier_panier_block_storage", value)
			} else if value.Valid {
				pbs.panier_panier_block_storage = new(int)
				*pbs.panier_panier_block_storage = int(value.Int64)
			}
		default:
			pbs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PanierBlockStorage.
// This includes values selected through modifiers, order, etc.
func (pbs *PanierBlockStorage) Value(name string) (ent.Value, error) {
	return pbs.selectValues.Get(name)
}

// QueryPanier queries the "panier" edge of the PanierBlockStorage entity.
func (pbs *PanierBlockStorage) QueryPanier() *PanierQuery {
	return NewPanierBlockStorageClient(pbs.config).QueryPanier(pbs)
}

// QueryBlockStorage queries the "blockStorage" edge of the PanierBlockStorage entity.
func (pbs *PanierBlockStorage) QueryBlockStorage() *BlockStorageQuery {
	return NewPanierBlockStorageClient(pbs.config).QueryBlockStorage(pbs)
}

// Update returns a builder for updating this PanierBlockStorage.
// Note that you need to call PanierBlockStorage.Unwrap() before calling this method if this PanierBlockStorage
// was returned from a transaction, and the transaction was committed or rolled back.
func (pbs *PanierBlockStorage) Update() *PanierBlockStorageUpdateOne {
	return NewPanierBlockStorageClient(pbs.config).UpdateOne(pbs)
}

// Unwrap unwraps the PanierBlockStorage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pbs *PanierBlockStorage) Unwrap() *PanierBlockStorage {
	_tx, ok := pbs.config.driver.(*txDriver)
	if !ok {
		panic("ent: PanierBlockStorage is not a transactional entity")
	}
	pbs.config.driver = _tx.drv
	return pbs
}

// String implements the fmt.Stringer.
func (pbs *PanierBlockStorage) String() string {
	var builder strings.Builder
	builder.WriteString("PanierBlockStorage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pbs.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", pbs.Quantity))
	builder.WriteByte(')')
	return builder.String()
}

// PanierBlockStorages is a parsable slice of PanierBlockStorage.
type PanierBlockStorages []*PanierBlockStorage
