// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/panier"
	"backend/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	panierFields := schema.Panier{}.Fields()
	_ = panierFields
	// panierDescUID is the schema descriptor for uid field.
	panierDescUID := panierFields[0].Descriptor()
	// panier.DefaultUID holds the default value on creation for the uid field.
	panier.DefaultUID = panierDescUID.Default.(func() uuid.UUID)
}
