// Code generated by ent, DO NOT EDIT.

package panierblockstorage

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the panierblockstorage type in the database.
	Label = "panier_block_storage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// EdgePanier holds the string denoting the panier edge name in mutations.
	EdgePanier = "panier"
	// EdgeBlockStorage holds the string denoting the blockstorage edge name in mutations.
	EdgeBlockStorage = "blockStorage"
	// Table holds the table name of the panierblockstorage in the database.
	Table = "panier_block_storages"
	// PanierTable is the table that holds the panier relation/edge.
	PanierTable = "panier_block_storages"
	// PanierInverseTable is the table name for the Panier entity.
	// It exists in this package in order to avoid circular dependency with the "panier" package.
	PanierInverseTable = "paniers"
	// PanierColumn is the table column denoting the panier relation/edge.
	PanierColumn = "panier_panier_block_storage"
	// BlockStorageTable is the table that holds the blockStorage relation/edge.
	BlockStorageTable = "panier_block_storages"
	// BlockStorageInverseTable is the table name for the BlockStorage entity.
	// It exists in this package in order to avoid circular dependency with the "blockstorage" package.
	BlockStorageInverseTable = "block_storages"
	// BlockStorageColumn is the table column denoting the blockStorage relation/edge.
	BlockStorageColumn = "block_storage_panier_block_storage"
)

// Columns holds all SQL columns for panierblockstorage fields.
var Columns = []string{
	FieldID,
	FieldQuantity,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "panier_block_storages"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"block_storage_panier_block_storage",
	"panier_panier_block_storage",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the PanierBlockStorage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByPanierField orders the results by panier field.
func ByPanierField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPanierStep(), sql.OrderByField(field, opts...))
	}
}

// ByBlockStorageField orders the results by blockStorage field.
func ByBlockStorageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlockStorageStep(), sql.OrderByField(field, opts...))
	}
}
func newPanierStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PanierInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PanierTable, PanierColumn),
	)
}
func newBlockStorageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlockStorageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BlockStorageTable, BlockStorageColumn),
	)
}
