// Code generated by ent, DO NOT EDIT.

package panierblockstorage

import (
	"backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldLTE(FieldID, id))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldEQ(FieldQuantity, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(sql.FieldLTE(FieldQuantity, v))
}

// HasPanier applies the HasEdge predicate on the "panier" edge.
func HasPanier() predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PanierTable, PanierColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPanierWith applies the HasEdge predicate on the "panier" edge with a given conditions (other predicates).
func HasPanierWith(preds ...predicate.Panier) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		step := newPanierStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBlockStorage applies the HasEdge predicate on the "blockStorage" edge.
func HasBlockStorage() predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BlockStorageTable, BlockStorageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBlockStorageWith applies the HasEdge predicate on the "blockStorage" edge with a given conditions (other predicates).
func HasBlockStorageWith(preds ...predicate.BlockStorage) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		step := newBlockStorageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PanierBlockStorage) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PanierBlockStorage) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PanierBlockStorage) predicate.PanierBlockStorage {
	return predicate.PanierBlockStorage(func(s *sql.Selector) {
		p(s.Not())
	})
}
