// Code generated by ent, DO NOT EDIT.

package ipaddress

import (
	"backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "Name" field. It's identical to NameEQ.
func Name(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldName, v))
}

// Price applies equality check predicate on the "Price" field. It's identical to PriceEQ.
func Price(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldPrice, v))
}

// NameEQ applies the EQ predicate on the "Name" field.
func NameEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "Name" field.
func NameNEQ(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "Name" field.
func NameIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "Name" field.
func NameNotIn(vs ...string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "Name" field.
func NameGT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "Name" field.
func NameGTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "Name" field.
func NameLT(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "Name" field.
func NameLTE(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "Name" field.
func NameContains(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "Name" field.
func NameHasPrefix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "Name" field.
func NameHasSuffix(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "Name" field.
func NameEqualFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "Name" field.
func NameContainsFold(v string) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldContainsFold(FieldName, v))
}

// PriceEQ applies the EQ predicate on the "Price" field.
func PriceEQ(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "Price" field.
func PriceNEQ(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "Price" field.
func PriceIn(vs ...float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "Price" field.
func PriceNotIn(vs ...float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "Price" field.
func PriceGT(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "Price" field.
func PriceGTE(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "Price" field.
func PriceLT(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "Price" field.
func PriceLTE(v float64) predicate.IPAddress {
	return predicate.IPAddress(sql.FieldLTE(FieldPrice, v))
}

// HasPanierIPAddress applies the HasEdge predicate on the "panierIPAddress" edge.
func HasPanierIPAddress() predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PanierIPAddressTable, PanierIPAddressColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPanierIPAddressWith applies the HasEdge predicate on the "panierIPAddress" edge with a given conditions (other predicates).
func HasPanierIPAddressWith(preds ...predicate.PanierIPAddress) predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		step := newPanierIPAddressStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IPAddress) predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IPAddress) predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IPAddress) predicate.IPAddress {
	return predicate.IPAddress(func(s *sql.Selector) {
		p(s.Not())
	})
}
